-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 01, 2022 at 07:26 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ecommerce`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `SKU` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `details` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` double(8,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `slug`, `SKU`, `details`, `image`, `price`, `created_at`, `updated_at`) VALUES
(1, 'Prof.', 'soluta', 'Soluta.', 'Nostrum aut necessitatibus cum ullam accusamus voluptatem atque esse. Nulla aut eos facere sapiente aut. Quo eos velit magnam id consequuntur nisi nesciunt. Laudantium quia culpa nam ut vel neque ut.', 'Necessitatibus temporibus iure accusamus iste. Accusantium aliquid amet non ut perferendis unde. Quisquam ducimus velit velit harum. Sint porro iusto est qui.', 273.50, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(2, 'Mrs.', 'et-cum', 'Et cum.', 'Veniam possimus qui possimus explicabo aut. Et dolor voluptatem quia omnis et modi sunt quis. Nobis magnam quia repudiandae accusamus et.', 'Molestiae veniam qui doloremque minima omnis quia. Temporibus nihil nostrum inventore. Sed vel non accusantium quo consequuntur saepe aut.', 687.00, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(3, 'Dr.', 'culpa', 'Culpa.', 'Qui et porro eveniet aut. Quaerat nemo at aliquam autem placeat.', 'Alias odit provident minima voluptas ipsam. Assumenda possimus non perspiciatis molestias vero quo. Repellendus autem perspiciatis earum. Et repellendus saepe ullam inventore et dignissimos ex.', 1489.68, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(4, 'Dr.', 'quasi', 'Quasi.', 'Est vel est minima saepe voluptatem. Eligendi est quibusdam aut debitis quae. Sapiente saepe ex beatae a nostrum ea modi. Nobis enim aspernatur voluptatum sed dolores harum.', 'Magni sunt dignissimos eos earum. Laborum cupiditate tenetur distinctio nihil voluptatem. Enim sequi reiciendis quisquam est rerum quia quas. Ad est dolorem est voluptas sed inventore cum.', 1022.35, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(5, 'Ms.', 'enim', 'Enim.', 'Repellat laudantium et atque ducimus. Et aut dolores fuga et reiciendis. Quia et ratione fuga unde optio et expedita. Delectus mollitia sed qui delectus quis et sequi.', 'Ut quo officiis vero. Omnis necessitatibus velit ipsum ut sed dolores. Enim perspiciatis explicabo reiciendis eos sunt.', 875.33, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(6, 'Mrs.', 'minima', 'Minima.', 'Dolor et repudiandae facilis. Non autem quo nihil qui laborum dolor. Vitae dolor voluptatibus voluptatem ut et voluptates sed. Nulla blanditiis in ipsum in quia.', 'Dolorum natus incidunt optio architecto aut. Eligendi hic illum nihil autem sint. Quam iusto qui possimus voluptatibus ducimus.', 1498.58, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(7, 'Ms.', 'tempore', 'Tempore.', 'Et dicta quisquam non cumque esse perferendis magni nihil. Explicabo perspiciatis corrupti veritatis ea. Iure unde consequatur sit ut ut cum est asperiores.', 'Laudantium blanditiis quia minus quia ut neque facilis. Explicabo eius vel quod odit vero unde recusandae.', 76.64, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(8, 'Mr.', 'minus', 'Minus.', 'Nisi molestiae ea architecto. Rerum totam neque est deleniti delectus ipsum. Nostrum ut amet beatae dolorem facere veritatis molestias.', 'Mollitia sapiente in deserunt necessitatibus. Blanditiis pariatur accusamus perspiciatis. Sint hic consequatur mollitia quia voluptates.', 584.84, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(9, 'Prof.', 'ut-enim', 'Ut enim.', 'Totam quia hic maiores possimus rerum excepturi. Ipsa et voluptate optio ab. Rerum blanditiis asperiores et. Perspiciatis earum voluptatem corporis et. Atque officia similique dolorem at.', 'Blanditiis aut nisi velit animi velit. Ut quos repellat voluptas voluptatem unde impedit. Numquam cupiditate quod dignissimos fugiat perferendis.', 625.18, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(10, 'Mrs.', 'libero', 'Libero.', 'Dolor non ex rerum earum. Voluptatum vel consequuntur sapiente sed.', 'Commodi mollitia in corrupti aut voluptas similique et. Sunt cum accusamus dolor autem at voluptatem. Molestiae dicta voluptatem qui pariatur vel inventore soluta.', 1173.99, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(11, 'Prof.', 'natus', 'Natus.', 'Id vitae deserunt corporis quidem ipsam ipsum consequatur consectetur. Est ut cupiditate aperiam voluptas rerum molestiae dolorum. Nobis in occaecati voluptatum tempore enim et impedit consequuntur. Culpa eaque tempora rerum distinctio quas occaecati id placeat.', 'Blanditiis excepturi possimus quo. Ut ut quia labore praesentium harum. Porro ut rerum facere dolores natus consequatur. Et animi dolore quo officia velit accusantium ut ea.', 788.14, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(12, 'Dr.', 'dicta', 'Dicta.', 'Enim voluptate at qui. Officia non id doloribus fugiat eum quo harum error. Est perferendis ut dicta debitis. Minima vel et optio sed.', 'Fugiat voluptas quidem qui nam laboriosam. Tempora beatae quia necessitatibus voluptas nemo fugit. Laboriosam animi nemo magni quaerat. Voluptas quisquam aut tempore iure autem.', 807.08, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(13, 'Ms.', 'aut', 'Aut.', 'Sequi dolorum sit minus quis. Et consequatur praesentium laborum doloribus odio. Hic aut inventore officia. Velit necessitatibus architecto minus exercitationem voluptatem et similique omnis.', 'Earum id reprehenderit labore sed. Sed assumenda iusto iusto neque. Neque error aut minima ullam velit. Animi praesentium culpa molestiae ab similique consequatur et.', 1901.80, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(14, 'Miss', 'modi', 'Modi.', 'Nostrum ipsa porro id vero. Consectetur eligendi aut dicta asperiores eos. Neque ea qui facilis porro ipsum odio. Eaque odit debitis consequuntur sequi nulla vel.', 'Tenetur vitae sequi ut laborum. Doloremque exercitationem iure dolores. Delectus debitis qui non dicta. Ut nostrum maiores officiis dolor vel qui.', 9.16, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(15, 'Prof.', 'totam', 'Totam.', 'Cupiditate aut dolorem sunt cupiditate voluptate atque rerum. Dolorem repellat provident aliquid quibusdam ut. Natus quo laboriosam laborum sit aut accusantium perferendis harum.', 'Et alias labore laudantium repellat. Dicta quia fugiat minus nemo itaque iusto. Ut nihil architecto tempore sit accusantium vitae eum.', 956.69, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(16, 'Miss', 'iure', 'Iure.', 'Molestias corporis eius aut. A dolores consectetur odit iure laudantium recusandae perferendis. Id quae repellendus officiis saepe. Illum nulla quod quibusdam.', 'Libero itaque odio dolorem placeat optio. Molestiae rerum rerum consequatur deleniti dolorem. Ad rerum incidunt ullam. Quo ut provident nam aut natus vitae.', 1337.72, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(17, 'Dr.', 'est', 'Est.', 'Officiis non et praesentium impedit repudiandae. Odio ducimus aperiam ut occaecati vero et nulla. Voluptatum mollitia aliquid est. Laborum suscipit facere molestiae et voluptatem.', 'Voluptas dolore ut ex odio quibusdam qui. Iusto optio sed aut voluptas tenetur quia. Nam incidunt omnis distinctio quia totam.', 497.19, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(18, 'Prof.', 'aperiam', 'Aperiam.', 'Harum magnam doloremque commodi blanditiis perspiciatis. Est quas vero voluptas dolorum nesciunt ut consectetur. Libero rerum molestias et dolores aut qui nostrum. Ex aperiam commodi repellendus qui dolor.', 'Qui voluptates saepe itaque non tempora. Officia incidunt est et voluptatem sed. Eaque eos et omnis quis veniam ratione. Minus quo quam unde voluptate voluptas distinctio debitis.', 500.20, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(19, 'Mrs.', 'quod', 'Quod.', 'Cum laudantium autem exercitationem. Fugit laudantium incidunt et. Distinctio fugit explicabo atque qui suscipit voluptatem eos.', 'Maxime ipsa possimus sequi. Vitae minus ullam totam optio. Quia magnam qui earum atque ut dolores. Et voluptas quasi nesciunt.', 913.00, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(20, 'Dr.', 'nemo', 'Nemo.', 'Excepturi modi aut quaerat sed pariatur. Dolores numquam voluptas eveniet voluptatem quia molestiae nihil rerum. Quo voluptas est non cum.', 'Est dolorem dolorem sint rerum iste. Corporis voluptas nam ut reprehenderit sapiente inventore in ut. Eos quibusdam illo et laborum.', 336.02, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(21, 'Miss', 'ut-et', 'Ut et.', 'Sunt quam minus ut quis aut veritatis. Dolorem dicta autem aut.', 'Repellat ducimus est dolorum facilis dolor nam. Qui tempore eum non voluptas atque aspernatur. Dicta nostrum reiciendis a quod ad. Harum voluptas aliquam perferendis.', 93.69, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(22, 'Dr.', 'ab-sed', 'Ab sed.', 'Consequatur velit a sunt corporis dolores doloribus commodi. Facilis vel rerum voluptate temporibus sed dolores. Eum repellendus suscipit consequuntur voluptatem necessitatibus sit neque atque. Maxime et consequatur unde.', 'Facere itaque non laboriosam sint in. Amet eveniet fugit eum iusto. Beatae consequatur ut libero.', 1349.15, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(23, 'Prof.', 'porro', 'Porro.', 'Perspiciatis dignissimos nihil est veritatis excepturi iure deserunt. Minima et sint quam velit blanditiis.', 'Ut placeat sapiente nesciunt. Quia deleniti natus necessitatibus aut odit.', 975.00, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(24, 'Mrs.', 'sit', 'Sit.', 'Corrupti labore eos dolores dignissimos fugit omnis ut. Sed necessitatibus non odio voluptatem voluptas. Dolore ut et ut nisi id veniam. Eum voluptas eum ut error aliquid earum eos ipsa.', 'Neque odio quibusdam voluptatem quia eaque. Facere id officiis id. Corporis impedit nesciunt enim quo quis totam. Atque est in consequatur quia neque deserunt.', 240.00, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(25, 'Dr.', 'beatae', 'Beatae.', 'Quos ipsam deleniti delectus dolor. Nemo quia excepturi dolores quia animi tenetur optio. Id fuga officiis culpa consequatur assumenda.', 'Quo reiciendis cupiditate mollitia hic id. Unde alias deleniti voluptatem ipsa et. Temporibus et non rerum voluptas suscipit. Tempore aut est vero dolorem odit voluptatem.', 400.41, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(26, 'Miss', 'nostrum', 'Nostrum.', 'Laudantium commodi dignissimos enim quod quia quia. Architecto voluptatibus repudiandae facere eveniet sit sed. Deleniti unde odit occaecati vel.', 'Vitae accusamus ratione odit distinctio corrupti. Eum aut debitis quasi voluptatem qui. Perferendis blanditiis qui blanditiis et commodi iusto. Ratione nisi consequatur sed maiores eligendi quidem.', 1155.66, '2022-10-31 22:37:55', '2022-10-31 22:37:55'),
(28, 'Mrs.', 'qui-et', 'Qui et.', 'Ut est repudiandae sequi enim laborum asperiores voluptates est. Voluptatem dignissimos vel nam. Quod hic sapiente perferendis qui voluptatum accusamus.', 'Vitae deleniti sed qui quo. Ipsam fugiat repellat accusantium facere corporis aut. Facilis dicta est mollitia.', 402.00, '2022-10-31 22:37:57', '2022-10-31 22:37:57'),
(30, 'Mrs.', 'earum', 'Earum.', 'Inventore et iusto error nam saepe voluptatem quia non. Cupiditate animi tempore accusamus et ad quia officiis aut. Cumque sunt quia et exercitationem. Nostrum quos eaque sed.', 'Sint dicta ut sunt quo quia maxime facilis. Quia labore aut omnis quibusdam vero et. Accusamus recusandae quasi atque at numquam ea. Iure laboriosam quia et qui ex illum molestiae.', 1766.22, '2022-10-31 22:37:58', '2022-10-31 22:37:58'),
(31, 'Dr.', 'rerum', 'Rerum.', 'Architecto sed provident magnam voluptate illum laudantium. Cumque voluptatibus fugit ut accusamus et quam et. Qui nisi eos vitae doloremque.', 'Non repellat quia atque necessitatibus eligendi ex ab. Quam nobis quae molestiae.', 1813.35, '2022-10-31 22:37:58', '2022-10-31 22:37:58'),
(33, 'Ms.', 'quos', 'Quos.', 'Sunt voluptas blanditiis aut. Quibusdam cupiditate dignissimos et ullam aut omnis non qui. Ex fugit voluptate veniam ut recusandae voluptas magni ipsa.', 'Quae saepe ratione unde et doloribus. Ut consequatur consequatur ex ea explicabo sed et.', 1860.69, '2022-10-31 22:37:59', '2022-10-31 22:37:59'),
(36, 'Mr.', 'eveniet', 'Eveniet.', 'Est nemo minima quia laudantium. Quam nulla non sunt unde fugiat odit facere. Quis adipisci autem nulla dolor.', 'Est provident magnam neque quia est alias. Iste labore natus aspernatur debitis qui. Harum atque fugiat dolorem et aliquid.', 1122.00, '2022-10-31 22:38:02', '2022-10-31 22:38:02'),
(38, 'Dr.', 'velit', 'Velit.', 'Pariatur dolores aliquam dolorem vitae autem. Cupiditate vitae repellat repellendus sint. Et maiores expedita voluptatem id placeat fugiat et. Cupiditate exercitationem est eius perferendis eius impedit eligendi expedita.', 'Molestiae pariatur dolore temporibus nostrum ab tempora. Reprehenderit architecto illum et iure atque sapiente. Et architecto vitae dolore.', 414.70, '2022-10-31 22:38:03', '2022-10-31 22:38:03'),
(39, 'Dr.', 'sequi', 'Sequi.', 'Cupiditate et reiciendis ipsum culpa cumque fugit. Ducimus id voluptate commodi reiciendis. Dolores laudantium dolore perferendis quas.', 'Laudantium soluta saepe consequatur quo voluptatem quasi natus voluptatem. Nihil qui odio asperiores assumenda porro qui. Voluptatum reiciendis sit ab. Deleniti nulla unde quo ut itaque.', 1236.35, '2022-10-31 22:38:03', '2022-10-31 22:38:03'),
(40, 'Ms.', 'facere', 'Facere.', 'Voluptates suscipit optio numquam inventore qui. Quos eos dignissimos repellendus totam sed qui ex. Sunt officia iure doloremque sint.', 'Autem adipisci dolore molestiae. Qui pariatur dolores velit quam magni.', 362.68, '2022-10-31 22:38:03', '2022-10-31 22:38:03'),
(42, 'Dr.', 'error', 'Error.', 'Aliquid animi repellat voluptate natus. Quidem voluptas laborum voluptatem. Repellat rem explicabo impedit eum suscipit culpa. Expedita illo laborum amet impedit eos sunt.', 'Sint et sint consequuntur ipsam eius. Rerum voluptatem aut dolorem aliquid quo ut. Consequatur et ullam impedit corporis. Est voluptas asperiores est laudantium.', 581.53, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(43, 'Mr.', 'est-qui', 'Est qui.', 'Quia illum ipsa doloribus. Quo est alias sed eum assumenda incidunt. Sit ea velit iste tenetur atque aut.', 'Architecto illo eaque sint impedit cupiditate minus. Ea possimus rerum est cumque dignissimos quisquam. Aut corrupti sint totam. Et ex qui voluptatem distinctio tenetur.', 597.64, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(44, 'Ms.', 'et', 'Et.', 'Ex ullam est illum adipisci non vero adipisci. Aperiam qui et aliquam distinctio. A aliquam maiores laudantium velit. Velit et qui qui dolorem soluta fugit debitis.', 'Aut culpa exercitationem in eaque qui ut quae hic. Ipsam maxime aut eum. Atque doloribus quia possimus odio. Saepe nesciunt adipisci tempora dolorem voluptatem suscipit.', 1396.33, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(45, 'Mr.', 'placeat', 'Placeat.', 'In voluptates repudiandae maiores distinctio qui magni veniam. Dicta ab sapiente non beatae ea necessitatibus reprehenderit. Ratione deserunt dolor vitae aut.', 'Eveniet qui harum excepturi necessitatibus non. Sit tenetur sit ad iure. Qui quaerat beatae reprehenderit tempora fugit. Recusandae non quis quos placeat.', 1967.70, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(46, 'Ms.', 'sed', 'Sed.', 'Rem qui doloribus et ut quam. Vel autem velit similique quia et. Dolor sapiente ex non maxime qui.', 'Et aut repellendus sint quod. Voluptatem vel voluptatum est ut tenetur nihil est. Repellendus dolorum sed vero fuga ut. Sit impedit in ratione sit molestiae eveniet omnis.', 623.26, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(47, 'Dr.', 'optio', 'Optio.', 'Debitis rerum consequatur non repudiandae dicta. Molestias occaecati deleniti alias qui aut dolor nulla. Adipisci voluptates harum sit.', 'Voluptatum recusandae nemo reprehenderit exercitationem maiores quas et. Rem rerum velit quis accusamus. Nobis qui similique est quidem.', 1256.16, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(48, 'Dr.', 'sint', 'Sint.', 'Consequatur animi dolorem consectetur magni. Maxime voluptatum qui ut ducimus. Dicta molestiae cupiditate exercitationem autem animi. Vel ipsa veniam labore libero eveniet sint.', 'Omnis qui et tempore voluptatibus similique illum. Tenetur nesciunt aut in veniam. Quam ipsa quia laboriosam voluptatem.', 1409.92, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(49, 'Miss', 'eos', 'Eos.', 'Maiores qui rerum maxime dolor est. Qui voluptas qui molestiae quis excepturi sint dolores. Cupiditate laboriosam nemo autem aut corrupti libero commodi. Ab quo culpa qui perspiciatis mollitia eligendi.', 'Repellat non ipsam dolor aut blanditiis. In natus culpa quam occaecati. Quae libero expedita sint veritatis temporibus. Ut quas aliquam est nihil error.', 664.40, '2022-10-31 22:38:04', '2022-10-31 22:38:04'),
(51, 'Prof.', 'a-est', 'A est.', 'Consequatur ipsam officiis sit eos voluptatum et. Doloremque quia nesciunt reiciendis ad excepturi. Aut nesciunt dolorem ut accusantium.', 'Harum nemo omnis rem tempora sint quo consectetur. Eum sed ex a id excepturi. Qui sunt adipisci velit aut perferendis esse.', 1347.61, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(52, 'Mr.', 'nisi', 'Nisi.', 'Debitis voluptas et illum et tempore corrupti quibusdam. Sit saepe rem magni porro dolor repellat quod ipsa. Possimus non numquam aliquid soluta tempora natus. Non odio enim praesentium est.', 'Eum nam quia assumenda eum rem sunt ut. Quia nihil sapiente ea. Non esse rerum fugit pariatur laboriosam sit quae. Non quod et consequuntur et voluptas doloribus. Maiores et voluptatem omnis veniam.', 1010.03, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(53, 'Dr.', 'id', 'Id.', 'Quo et excepturi quo pariatur nisi. Totam eaque modi tempore consequatur quia. Est hic eveniet quaerat et hic placeat laborum.', 'Eveniet ut qui qui temporibus dolor incidunt. In id doloremque consequatur ad qui.', 972.52, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(54, 'Prof.', 'quidem', 'Quidem.', 'Sit dolores quas natus. Earum veritatis quasi nihil incidunt. Et et et a qui nihil animi. Dignissimos enim a accusantium sed in et dolores aut.', 'Est ut explicabo aperiam. Aut distinctio inventore facilis. Explicabo repellendus aperiam dolor accusamus. Aspernatur eius nulla et occaecati unde in eum.', 576.93, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(55, 'Prof.', 'ut', 'Ut.', 'Quo unde aut repudiandae nostrum aperiam optio. Quia ut at id pariatur laboriosam. Velit voluptatum earum dolorum praesentium. Pariatur sed ut perferendis molestias.', 'Tempore voluptatem aut vel qui. Veritatis quia esse error voluptatem sint est nisi. Consequatur numquam excepturi nemo sint vero saepe repellat explicabo.', 1955.71, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(56, 'Mrs.', 'autem', 'Autem.', 'Vel voluptas aut nesciunt ab. Omnis at qui eveniet impedit dolorem dicta ut. Neque optio sint molestiae sed. Quae quia rerum omnis consequatur. Eveniet sint enim voluptas sunt quia eligendi nesciunt ad.', 'Ea nemo illo est explicabo. Doloribus qui laboriosam est sunt eveniet.', 1813.90, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(57, 'Prof.', 'et-quia', 'Et quia.', 'Quia nisi tenetur voluptas veritatis ea. Qui totam quia in omnis totam. Ex qui aperiam aut est modi in aut.', 'Velit aut exercitationem corrupti quisquam earum. Sint et qui laborum illo. Magni voluptatem quasi temporibus. Saepe nihil reiciendis quisquam culpa.', 921.62, '2022-10-31 22:38:13', '2022-10-31 22:38:13'),
(61, 'Prof.', 'quia', 'Quia.', 'Officiis fuga quasi repellendus sint commodi et qui. Quia rerum et quam temporibus omnis. Quia reiciendis ducimus distinctio qui doloremque illum molestiae. Reprehenderit voluptates illo consequatur a at asperiores expedita.', 'Animi quam molestias similique ut id. Similique voluptatum pariatur repellendus quia quasi nobis. Sit dolor et fugiat enim. Provident architecto nemo voluptate totam vitae fuga vel.', 158.18, '2022-10-31 22:38:30', '2022-10-31 22:38:30'),
(62, 'Miss', 'nihil', 'Nihil.', 'Optio dicta facere aliquam ratione a asperiores. Ex nesciunt rerum ab omnis. Consequuntur cumque nam molestias eligendi mollitia quisquam ducimus. Aperiam beatae repellat qui quia sunt.', 'Expedita quos sed nihil numquam modi eos. Et qui ut consequuntur illum non voluptas est. Nulla doloremque qui unde officiis porro est sed.', 1983.36, '2022-10-31 22:38:30', '2022-10-31 22:38:30'),
(63, 'Dr.', 'quis', 'Quis.', 'Aut et esse saepe porro rerum officiis. Repellendus quia quos rem perspiciatis laboriosam. Molestias dolores et quia et. Aperiam enim repudiandae qui dolor et omnis magnam aspernatur.', 'Eum quam eos beatae dolores. Debitis totam sit quia tempora et at. Voluptas saepe ut maiores incidunt. Illo atque tempore ut suscipit doloribus necessitatibus.', 1244.95, '2022-10-31 22:38:30', '2022-10-31 22:38:30'),
(64, 'Mr.', 'fugit', 'Fugit.', 'Omnis laboriosam corporis et occaecati tenetur corrupti cupiditate. Odio voluptatibus mollitia recusandae. Quia repellendus numquam nemo et.', 'Non consectetur unde ipsam itaque. Reprehenderit nihil magnam nam eaque sint et. Minus nisi quo eum aspernatur sint cumque est.', 1986.74, '2022-10-31 22:38:30', '2022-10-31 22:38:30'),
(65, 'Ms.', 'quas', 'Quas.', 'Ut sit rerum qui facilis occaecati. Reiciendis repellendus aut exercitationem distinctio qui. Aspernatur ipsa corrupti sapiente dolor sed totam ea. Quam suscipit rerum sit eum repellendus id officia ex. Similique consequatur qui temporibus voluptas dignissimos rerum.', 'Et aut quo eveniet consectetur fugiat ducimus blanditiis libero. Qui delectus nam nihil. Eligendi esse reiciendis laborum atque assumenda omnis itaque. Harum ratione iure totam soluta illo officiis.', 1422.79, '2022-10-31 22:38:30', '2022-10-31 22:38:30'),
(67, 'Dr.', 'cumque', 'Cumque.', 'Quisquam quis quo eum illo ea nemo. Ut iste dolorem et molestias a iusto. Nesciunt impedit et consequuntur cumque. Explicabo omnis laboriosam illum et ut.', 'Et occaecati est consequatur voluptatem explicabo quaerat. Sit quisquam dolores qui voluptas sint illo. Qui ex aspernatur in maiores deserunt. Quo sunt commodi velit sed est et excepturi.', 701.69, '2022-10-31 22:38:31', '2022-10-31 22:38:31'),
(68, 'Dr.', 'iusto', 'Iusto.', 'Itaque eveniet inventore rem error rerum temporibus illum. Quibusdam dolore consequatur modi consequatur eveniet non dolorum. Nihil molestiae aliquid atque est qui.', 'Id distinctio ea illum quod temporibus. Magni et eum quia inventore fuga totam. Ea architecto dignissimos assumenda magnam.', 1998.34, '2022-10-31 22:38:31', '2022-10-31 22:38:31'),
(69, 'Dr.', 'ut-qui', 'Ut qui.', 'Officiis temporibus sed sed rerum consequatur nulla. Excepturi repellat totam quia rerum et enim rerum. Asperiores magni sint omnis occaecati.', 'Est expedita id eum est. At eius cupiditate quis in eos qui necessitatibus. Ad beatae omnis consequatur molestiae voluptatibus.', 758.60, '2022-10-31 22:38:31', '2022-10-31 22:38:31'),
(73, 'Dr.', 'illum', 'Illum.', 'Eos quisquam maiores deleniti animi voluptatem laborum sed. Qui praesentium natus et cum est fugit voluptatibus. Iste dolore voluptas illum consequuntur ipsam et sit et. Tenetur amet non fuga id.', 'Nemo expedita corporis dicta non nesciunt laudantium. Corporis aliquam molestiae ad omnis ullam nemo. Aliquam expedita excepturi architecto.', 1596.57, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(74, 'Dr.', 'omnis', 'Omnis.', 'Sit rem sit aut non totam corrupti. Incidunt quae quo repellat deleniti ad dolore et. Quia pariatur porro similique odit.', 'Pariatur deleniti assumenda sunt esse. Expedita sunt voluptates totam quaerat quasi. Quia iusto debitis nulla et illum officia quibusdam. Quisquam corporis et est atque voluptatibus ea.', 1636.64, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(75, 'Mr.', 'et-et', 'Et et.', 'Et eum sint nemo odio qui. Veniam corrupti neque corrupti tempore quas nostrum est. Quos suscipit sint consequuntur vitae magnam voluptas. Beatae enim sit incidunt dolorem doloribus magnam dignissimos repellat. Et labore iusto tenetur nesciunt.', 'Enim aperiam deserunt et. Aut numquam accusantium fuga omnis dolor.', 94.90, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(76, 'Prof.', 'officia', 'Officia.', 'Et qui sed sed nesciunt aut. Nobis dolore repellendus laudantium exercitationem. Quia delectus et cumque. Suscipit ut error totam voluptas.', 'Corrupti eius et possimus recusandae aut quasi qui et. Dolorum numquam aliquid tempore earum nostrum et.', 628.50, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(77, 'Mrs.', 'non-quo', 'Non quo.', 'Quam ut unde et et. Nesciunt beatae vero et aut tempore et tenetur. Occaecati maxime laborum reprehenderit.', 'Fugiat deleniti nam nihil harum. Officia aut quam aperiam modi odit quis. Ducimus rerum molestiae beatae sed tenetur.', 929.14, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(78, 'Mrs.', 'quo', 'Quo.', 'Et et maiores laudantium modi tenetur aut. Vel harum nihil quia possimus. Doloribus voluptatem sed expedita eveniet.', 'Quia recusandae asperiores voluptate exercitationem soluta. Molestiae laudantium omnis numquam exercitationem non autem porro magnam. Numquam officiis aut rerum dolor.', 204.02, '2022-10-31 22:38:34', '2022-10-31 22:38:34'),
(81, 'Dr.', 'sunt', 'Sunt.', 'Fuga optio mollitia omnis molestiae quos nulla. Aut excepturi consequuntur placeat sit distinctio veniam. Optio impedit voluptatibus voluptate neque blanditiis cum sit consequatur. Qui et est provident explicabo officiis.', 'Recusandae at temporibus architecto et. Molestiae omnis molestiae tempora minima itaque et optio.', 486.00, '2022-10-31 22:38:36', '2022-10-31 22:38:36'),
(82, 'Mr.', 'qui', 'Qui.', 'Cum totam temporibus rerum ut consequuntur nobis ea. Vero sint in non voluptate. Et similique praesentium odio ipsum consequatur.', 'Atque et aut sapiente quam. Omnis tempora sequi non. Aut blanditiis doloremque impedit non eos et rem.', 1755.51, '2022-10-31 22:38:36', '2022-10-31 22:38:36'),
(85, 'Mr.', 'commodi', 'Commodi.', 'Sit hic mollitia magni. Ex est et velit sunt pariatur. Libero nostrum rem architecto fugiat et.', 'Porro quo omnis sint saepe consequatur in adipisci. Eius aspernatur veritatis dolores ducimus. Dolor id officia consequatur possimus et. Facilis ipsum eum quidem recusandae dolorem.', 645.75, '2022-10-31 22:38:37', '2022-10-31 22:38:37'),
(86, 'Prof.', 'unde', 'Unde.', 'Magnam ea eius id sed dolorem blanditiis fugit. Possimus voluptas iure tenetur cum vero adipisci earum ducimus. Ut nulla numquam maiores excepturi et.', 'Qui pariatur beatae in placeat dolorum blanditiis ullam repellat. Unde voluptas aut vitae neque. Dolorem quibusdam voluptates rem est.', 1305.46, '2022-10-31 22:38:37', '2022-10-31 22:38:37'),
(87, 'Mr.', 'et-non', 'Et non.', 'Quos eos ratione qui fuga. Reprehenderit magni maxime libero natus aut aut sit nihil. Dolor asperiores doloremque quia. Veniam corrupti quod facilis ut vel.', 'Sint vel minima illum odit libero omnis. Laborum et similique sint eaque veniam. Ex cum aut ut est sint.', 1274.94, '2022-10-31 22:38:37', '2022-10-31 22:38:37'),
(88, 'Prof.', 'fuga', 'Fuga.', 'Saepe blanditiis ut quam. Et fugit dicta soluta ipsam id ducimus quo. Omnis ad et voluptas non sunt quasi quia nobis.', 'Alias sed cum repellendus reprehenderit. Ea quam a perferendis neque iusto. Fugit aut provident et maxime eos.', 169.39, '2022-10-31 22:38:37', '2022-10-31 22:38:37'),
(97, 'Dr.', 'sed-eos', 'Sed eos.', 'Sint autem debitis velit eligendi. Autem voluptatum sit a sed quis officiis. Veritatis voluptas dolores nisi molestiae.', 'Sed rerum enim sit dicta. Pariatur consequatur rerum qui sit et. Ratione quibusdam soluta assumenda.', 303.49, '2022-10-31 22:38:48', '2022-10-31 22:38:48'),
(100, 'Mrs.', 'ab-hic', 'Ab hic.', 'Tenetur architecto tempore inventore tempore inventore delectus. Molestiae mollitia enim quod consequatur sint. Sint amet ullam qui possimus veritatis. Repudiandae ipsam quis qui sit cumque quos ipsum.', 'Voluptatibus beatae porro quis porro dolor. Voluptas atque provident sint beatae. Enim doloremque in ab corporis ipsum alias a.', 812.56, '2022-10-31 22:38:49', '2022-10-31 22:38:49'),
(101, 'Prof.', 'aut-qui', 'Aut qui.', 'Ea sed culpa quis distinctio quo animi ab. Praesentium possimus iusto commodi ipsa nihil occaecati distinctio. Non eveniet soluta quibusdam eum sed quas fugit. Delectus qui eligendi omnis dolorem nihil velit rerum.', 'Architecto voluptatem ipsum voluptatibus magnam ad fugit culpa. Suscipit rerum suscipit eveniet iste qui. Rerum dolores doloremque asperiores magni.', 970.40, '2022-10-31 22:38:49', '2022-10-31 22:38:49'),
(103, 'Prof.', 'ullam', 'Ullam.', 'Sunt fugiat odit vero exercitationem. Rerum et quis ipsam omnis. Quia quibusdam nobis sed quo nesciunt.', 'Odit id labore eum est facilis. Voluptatibus non tempore quia ut saepe. Totam quibusdam adipisci accusantium magni velit. Minus culpa dolor unde odit.', 1570.39, '2022-10-31 22:38:50', '2022-10-31 22:38:50'),
(104, 'Mrs.', 'ipsum', 'Ipsum.', 'Consequuntur perspiciatis totam incidunt aliquid molestiae eaque delectus eveniet. Quod vel eos doloremque. Sed aut est soluta dignissimos molestiae autem est et. Autem commodi animi et modi quibusdam ut quo.', 'Dolorem quo officiis debitis amet non non. Repudiandae blanditiis velit similique autem. Repellat itaque est et expedita.', 120.00, '2022-10-31 22:38:50', '2022-10-31 22:38:50'),
(105, 'Mr.', 'maxime', 'Maxime.', 'Dolor eius hic molestiae voluptas eos est consequuntur nesciunt. Nam sit quia assumenda voluptate. Ut pariatur temporibus ut veritatis quia. Vel aut non sint.', 'Similique debitis totam nesciunt accusantium itaque. Occaecati rerum doloremque voluptatem aliquid architecto accusantium. Maiores voluptatem rerum magnam molestiae qui laboriosam qui.', 11.86, '2022-10-31 22:38:50', '2022-10-31 22:38:50'),
(106, 'Dr.', 'dolores', 'Dolores.', 'Odio omnis iusto ut sequi rem in et. Ipsam et optio distinctio. Voluptas magnam provident eos officia saepe optio. Tenetur quos delectus aut ut et quo atque voluptas.', 'Nihil tempora libero dolor dolor numquam. Eius aut maxime et eum eius aperiam quis. Dignissimos deleniti expedita et. Quia amet praesentium placeat qui corrupti autem quia.', 72.43, '2022-10-31 22:38:50', '2022-10-31 22:38:50'),
(107, 'Mr.', 'hic-ex', 'Hic ex.', 'Quia itaque sed ut et provident aut voluptatem. Id beatae illum harum minus explicabo non debitis. Molestiae eum neque consequatur nostrum vero voluptatem nesciunt.', 'Porro ducimus fugiat error neque omnis. Aspernatur magnam quia sapiente dolore quia sed impedit. Sunt neque qui ut est eius.', 1405.02, '2022-10-31 22:38:50', '2022-10-31 22:38:50'),
(111, 'Prof.', 'ipsam', 'Ipsam.', 'Voluptates iure ut nulla amet autem error. Odit facilis deleniti libero tenetur. Ad aliquid optio et quia rerum neque.', 'Qui eveniet velit sed ut ea. A voluptas inventore quo itaque excepturi sit magnam. Voluptas sit nihil error natus sequi assumenda autem. Cupiditate itaque voluptas assumenda vitae sit.', 1295.70, '2022-10-31 22:38:51', '2022-10-31 22:38:51'),
(112, 'Prof.', 'magni', 'Magni.', 'Non sit debitis dolore incidunt ipsum quibusdam. Maiores velit exercitationem rem perferendis beatae dolor. Dolor debitis est aperiam dignissimos dolore nesciunt expedita.', 'Sint laboriosam reprehenderit sit dolorum omnis. Assumenda necessitatibus suscipit laboriosam provident rerum eos. In quidem nulla perspiciatis perferendis.', 1221.74, '2022-10-31 22:38:51', '2022-10-31 22:38:51'),
(117, 'Ms.', 'vel', 'Vel.', 'Similique quis qui a illum. Voluptatem harum accusamus exercitationem et quos accusamus assumenda autem. Excepturi sed et iure sit omnis omnis. Accusamus recusandae facere tenetur dolorum et.', 'Ab in et quis odio repellat. Et impedit odio accusantium ut atque. Beatae aut eum cum velit dolorem dignissimos illum.', 1007.12, '2022-10-31 22:38:53', '2022-10-31 22:38:53'),
(119, 'Prof.', 'tenetur', 'Tenetur.', 'Dicta quo rerum magni repellat. Omnis voluptatem qui id optio. Asperiores modi totam ut placeat. Voluptas amet sapiente asperiores vitae ea officiis.', 'Dolorem et ut doloribus. Necessitatibus aliquam et doloribus commodi ratione. Sed dolore ea voluptatum aut ut. Ipsum non pariatur eligendi ab rerum amet.', 539.12, '2022-10-31 22:38:54', '2022-10-31 22:38:54'),
(121, 'Miss', 'nam', 'Nam.', 'Voluptate neque alias aut. Et corporis voluptas voluptas vero. Voluptatem et non tempore vel est. Consequatur ducimus porro et exercitationem.', 'Reprehenderit ut magnam corrupti rerum qui. Voluptas quod ut magnam voluptas. Autem eum cupiditate ipsam aut consequatur. Ipsam rem aut quia facilis modi.', 1100.65, '2022-10-31 22:38:55', '2022-10-31 22:38:55'),
(123, 'Mr.', 'dolorem', 'Dolorem.', 'Fugit quo voluptas excepturi ab quis iusto aspernatur. Quo dignissimos molestiae tenetur dolorem in sequi iusto. Ex dolore iure omnis cumque recusandae.', 'Ex quo autem molestiae vero iste et quibusdam. Vel quia sunt qui molestiae qui aut. Necessitatibus dolorem vitae unde et repellat. Dolores fugiat et et pariatur dolor.', 1795.17, '2022-10-31 22:38:55', '2022-10-31 22:38:55'),
(124, 'Dr.', 'harum', 'Harum.', 'Iure voluptatem earum sint pariatur. Aut qui maiores itaque veniam qui optio et. Corrupti fugit velit atque at totam ratione sint. Non cupiditate facere nam voluptas voluptate architecto occaecati.', 'Deleniti id nemo blanditiis molestiae quam explicabo sed eveniet. Assumenda sed enim molestiae ipsum provident voluptas quod. Nisi sunt voluptatem consequuntur ut at accusantium.', 379.56, '2022-10-31 22:38:55', '2022-10-31 22:38:55'),
(125, 'Prof.', 'ut-non', 'Ut non.', 'Exercitationem voluptatem est id exercitationem sapiente et optio ut. Quo sint eligendi quo pariatur omnis quos. Dolores architecto eum nisi optio.', 'Deserunt et earum et ex vitae cum. Quam iste repudiandae omnis accusamus. Ab similique fugiat nemo quia ducimus.', 1302.90, '2022-10-31 22:38:55', '2022-10-31 22:38:55'),
(128, 'Miss', 'quae-ea', 'Quae ea.', 'Quis ipsa perspiciatis ex sed. Ut quia officiis iure adipisci sed id.', 'Velit consequatur earum fugiat tenetur inventore eius sit est. Fugiat nostrum veniam quasi. Illo vel est incidunt et et amet ut modi. Quia soluta enim ullam id.', 1062.20, '2022-10-31 22:39:01', '2022-10-31 22:39:01'),
(130, 'Dr.', 'est-sed', 'Est sed.', 'Alias officia delectus voluptate aut. Voluptas vero sed aut error consectetur. Quasi temporibus fugiat et dolore quisquam.', 'Odit non maiores id commodi. Quo corrupti voluptates veniam voluptatem sunt. Debitis eos inventore autem quia in.', 1364.00, '2022-10-31 22:39:02', '2022-10-31 22:39:02'),
(131, 'Mrs.', 'sed-in', 'Sed in.', 'Consectetur tempore minima ratione expedita ullam. Alias ea animi quia sed repellat rerum. Nemo non in iusto voluptas qui et.', 'Commodi explicabo quo sint voluptas. Voluptate quibusdam at libero. Natus minus atque excepturi reprehenderit. Aut modi reprehenderit ut.', 771.11, '2022-10-31 22:39:02', '2022-10-31 22:39:02'),
(134, 'Prof.', 'ipsa', 'Ipsa.', 'Voluptas rem optio quae consequatur vitae rerum ratione. Expedita quos qui sed praesentium voluptas voluptates amet. Quisquam et laboriosam necessitatibus et. Enim saepe et consectetur minus quod minus eos.', 'Aliquid minus ut commodi nostrum aut accusamus. Labore et quia provident deserunt non. Aut quo quasi eos. Deleniti excepturi aut aperiam quasi.', 902.85, '2022-10-31 22:39:03', '2022-10-31 22:39:03'),
(140, 'Mr.', 'tempora', 'Tempora.', 'Rerum non quos et quaerat nesciunt rerum quasi explicabo. Quod velit recusandae similique sequi qui soluta et. Omnis repudiandae consequatur magnam ut quis. Quia quia porro esse laborum repellat eligendi necessitatibus nulla.', 'Libero nesciunt sit quos deserunt in temporibus dolores. Excepturi et eum in aliquam est. Minima aperiam doloribus nesciunt.', 529.48, '2022-10-31 22:39:06', '2022-10-31 22:39:06'),
(141, 'Miss', 'ea-id', 'Ea id.', 'Nemo dolor voluptatum doloremque corporis voluptas voluptatem reiciendis. Sed id optio inventore id. Sit dolor necessitatibus itaque unde deleniti suscipit.', 'Ea nulla nisi ipsam. Doloremque officiis minima eos quam dolores. Voluptates et similique quas veniam eum sed. Maiores maiores culpa sed consequatur ut illum architecto.', 1673.53, '2022-10-31 22:39:06', '2022-10-31 22:39:06'),
(145, 'Prof.', 'labore', 'Labore.', 'Est sit placeat doloremque animi ut dolores fugit. Consequatur praesentium id culpa magnam dolorem eligendi at. Sapiente ipsum in aut quis error. Doloribus voluptas rerum dolor qui esse corporis corrupti.', 'Aliquam deserunt amet reprehenderit iure ratione minima rerum. Velit dignissimos ut et est sunt quis tempore. Et repellendus recusandae ea praesentium aliquam.', 494.20, '2022-10-31 22:39:09', '2022-10-31 22:39:09'),
(147, 'Prof.', 'et-sint', 'Et sint.', 'Architecto consequuntur debitis hic minus consequuntur nemo aut. Autem blanditiis qui sed nostrum tempore sed eos ut. Rerum rerum ea dolor autem nesciunt rem repellendus.', 'Quia qui excepturi rerum voluptatum in praesentium magni. Expedita incidunt quisquam impedit voluptatibus voluptas dolorum. Dolorem sint saepe vero tempore voluptatem asperiores.', 43.12, '2022-10-31 22:39:10', '2022-10-31 22:39:10'),
(151, 'Mr.', 'iste', 'Iste.', 'Excepturi distinctio incidunt modi non. Vero totam aut voluptatibus animi facere. Delectus impedit et quae qui debitis rerum.', 'Voluptatem modi molestiae accusamus. Error assumenda enim eligendi non aut. Laborum officia laboriosam magnam placeat architecto.', 1338.97, '2022-10-31 22:39:13', '2022-10-31 22:39:13'),
(153, 'Dr.', 'aut-sit', 'Aut sit.', 'Autem et quasi et at id. Eum velit non incidunt quo distinctio perferendis consequatur. Voluptatem quasi impedit animi voluptatibus deleniti voluptas. In sint voluptatum culpa in amet. Adipisci est pariatur perspiciatis repudiandae cupiditate omnis.', 'Officia eaque est laboriosam delectus ut. Nemo explicabo illum ducimus et doloribus.', 637.06, '2022-10-31 22:39:14', '2022-10-31 22:39:14'),
(157, 'Prof.', 'ea-enim', 'Ea enim.', 'Consequatur quae laudantium consequuntur dolor assumenda ducimus. Eveniet voluptas dolor error. Repellendus architecto error et. Nesciunt delectus nam nihil iusto nam.', 'Qui quis voluptas dolor soluta. Nobis consequatur et et dolor blanditiis doloribus rerum. Pariatur rerum fugit rerum vero magnam. Vero eveniet quos sapiente inventore.', 1559.26, '2022-10-31 22:39:20', '2022-10-31 22:39:20'),
(162, 'Mrs.', 'odit', 'Odit.', 'Ab aliquid voluptatem itaque sint labore. Dolores aliquam accusamus perspiciatis nostrum rerum autem. Fuga id sit voluptatem porro cum vitae architecto. Voluptatem iusto modi autem mollitia.', 'Quisquam eum soluta officia voluptatibus est quia perspiciatis. Ea a molestiae similique sequi. Qui eos facilis rerum mollitia. Aspernatur tempore mollitia explicabo consequuntur enim.', 1204.99, '2022-10-31 22:39:23', '2022-10-31 22:39:23'),
(163, 'Prof.', 'facilis', 'Facilis.', 'Dolore assumenda vel maxime qui. Omnis et voluptatum asperiores voluptatum modi. Odio accusantium tenetur et reprehenderit voluptas doloremque laborum. Voluptatum non quo sit ea quaerat ipsum.', 'Exercitationem id perferendis hic alias nobis. Et dolores beatae vero numquam. Molestiae consequuntur veritatis aut cumque omnis consequatur quis libero.', 548.16, '2022-10-31 22:39:23', '2022-10-31 22:39:23'),
(164, 'Ms.', 'ducimus', 'Ducimus.', 'Deleniti ad assumenda omnis qui quae iure. Sed facilis sequi nostrum modi. Voluptas rem facilis cumque et dolores qui. Necessitatibus maiores tempore aliquam sit sed aliquam sed. Quaerat quia veritatis explicabo a excepturi iste.', 'Excepturi asperiores veritatis unde natus. Sit qui quia tenetur amet quia sunt. Quos ut non occaecati voluptatem sed. Similique officiis blanditiis consequatur beatae totam.', 1524.98, '2022-10-31 22:39:23', '2022-10-31 22:39:23'),
(165, 'Prof.', 'et-odio', 'Et odio.', 'Quo quos aliquam numquam dolor quam repellendus itaque. Tempora maxime saepe non ipsum. Numquam aut inventore ut soluta sunt in et.', 'Eveniet amet aspernatur iste aut. Unde quas veritatis blanditiis tempore totam enim. Voluptatem et rerum dolores excepturi voluptate porro debitis. Dolorem veritatis nisi sit ex.', 1894.28, '2022-10-31 22:39:23', '2022-10-31 22:39:23'),
(166, 'Prof.', 'quia-et', 'Quia et.', 'In occaecati necessitatibus quaerat quis nihil accusamus id. Ut nam ea voluptas voluptas culpa voluptates sit. Aut at ipsum error ut ut.', 'Commodi optio est voluptas minima qui non. Nisi aut vitae consequuntur similique dicta. Fugit eos velit quos facilis sed. Id vero quo nulla saepe delectus. Non aspernatur et recusandae.', 52.08, '2022-10-31 22:39:23', '2022-10-31 22:39:23'),
(174, 'Prof.', 'non', 'Non.', 'Officiis rerum et id voluptatum nesciunt eaque ducimus. Quam voluptatem quam et est libero. Facere fugiat voluptate non delectus sint. Sint explicabo laborum corrupti ea qui.', 'Voluptatem ipsa et velit voluptatum. Odit accusamus rerum hic pariatur aut eveniet. Est aperiam accusantium incidunt.', 12.40, '2022-10-31 22:39:29', '2022-10-31 22:39:29'),
(175, 'Dr.', 'numquam', 'Numquam.', 'Dignissimos omnis perspiciatis aut quam quas deleniti. Debitis ab perferendis est illo dolores. Quis repellat aperiam sunt. Qui est accusantium soluta labore exercitationem.', 'Quo ut vel deserunt ad velit nam. Error laborum rerum nesciunt autem sequi amet. Culpa molestiae accusamus consequatur ea sunt.', 1661.14, '2022-10-31 22:39:29', '2022-10-31 22:39:29'),
(182, 'Mr.', 'quam', 'Quam.', 'Earum itaque rerum rerum qui illo velit. Corporis iure sit et reprehenderit. Cumque dolorem porro reprehenderit exercitationem et adipisci. Corporis quo facilis eum. Quidem inventore quisquam laboriosam quia dolore laborum culpa.', 'Facilis sed repellat qui molestias nihil. Voluptatibus accusantium aut non illum soluta earum. Laboriosam est voluptas nam eveniet pariatur qui amet.', 66.53, '2022-10-31 22:39:34', '2022-10-31 22:39:34'),
(184, 'Mrs.', 'non-ad', 'Non ad.', 'Et beatae saepe dicta debitis. Hic veniam sunt at et. Ex deleniti est neque et qui in. Sed sit et et ut.', 'Odit molestias sint voluptates. Maxime rerum iusto culpa. Quis mollitia earum sed fugit vero. Ducimus non ut nisi sit.', 1953.16, '2022-10-31 22:39:34', '2022-10-31 22:39:34'),
(188, 'Prof.', 'ad', 'Ad.', 'Nesciunt dolorum qui sed quaerat rerum. Non repudiandae consequatur quia suscipit asperiores enim. Et qui et aperiam nemo quibusdam sunt provident totam. Aliquam incidunt nulla eaque libero.', 'Sunt sapiente minima eum deserunt et natus deleniti rerum. Consectetur possimus quis voluptas. Tempora harum dolorem earum dolorem. Sunt provident ullam sunt consequatur.', 1567.65, '2022-10-31 22:39:37', '2022-10-31 22:39:37'),
(190, 'Dr.', 'aliquid', 'Aliquid.', 'Enim expedita itaque consequatur modi voluptate earum animi. Quaerat distinctio aut commodi autem ratione consectetur. Fuga officiis doloremque voluptatem quis alias voluptas. Dolores sed voluptatem eveniet velit totam dolorem vel eum.', 'Accusantium facilis natus corrupti sit maxime non. Sapiente aut vel qui. Quo saepe qui reprehenderit dolor.', 460.50, '2022-10-31 22:39:37', '2022-10-31 22:39:37'),
(191, 'Ms.', 'qui-eum', 'Qui eum.', 'Eius voluptatibus aperiam corrupti ipsa sunt. Quidem culpa aut quibusdam similique velit. Rerum alias ad quod non quasi veniam.', 'Est est vel eos et error explicabo. Id adipisci dicta at impedit. Illo corrupti adipisci ex necessitatibus.', 289.11, '2022-10-31 22:39:37', '2022-10-31 22:39:37'),
(195, 'Prof.', 'unde-ab', 'Unde ab.', 'Odio ducimus iure et tenetur rem. Accusamus ad aut nemo rem neque quia eos. Et dicta est quisquam ut aut aliquid hic eos. Velit voluptatum voluptate odit quia.', 'addidas-short.jpeg', 1363.79, '2022-10-31 22:39:39', '2022-10-31 22:41:29'),
(197, 'Dr.', 'at', 'At.', 'Ut occaecati eos quo neque similique. Autem ut vel quia architecto unde atque iure numquam. Et aut necessitatibus consequatur cumque. Illum assumenda repellat rerum et fuga et et in.', 'bersheka.jpg', 688.93, '2022-10-31 22:39:40', '2022-10-31 22:41:20'),
(200, 'Prof.', 'ut-id', 'Ut id.', 'Fuga et magnam doloremque perspiciatis. Voluptate sint ipsa consequatur qui tempora quo. Vel minus et consectetur quaerat.', 'nasa.jpg', 477.98, '2022-10-31 22:39:47', '2022-10-31 22:41:07'),
(203, 'visa', 'ajsdjsa', 'ajsdjsa', 'askdaksdkasdka', 'bersheka.jpg', 400.00, '2022-10-31 23:17:01', '2022-10-31 23:17:01'),
(204, 'hhjohyrdfd', 'gtygfr', 'gtygfr', 'fg t h gh hg', 'addidas-short.jpeg', 666.00, '2022-10-31 23:17:32', '2022-11-01 14:23:47'),
(205, 'sadj', 'jasid', 'jasid', 'adsasdka', 'nasa.jpg', 222.20, '2022-10-31 23:20:57', '2022-11-01 14:23:27'),
(206, 'asadss', 'asadss', 'asadss', 'asadss', 'bersheka.jpg', 222.00, '2022-10-31 23:22:49', '2022-11-01 14:23:35'),
(207, 'zambalek', 'zoma-zo', 'zoma zo', 'aksd jasdj asjdajs djas', 'nasa.jpg', 340.30, '2022-11-01 16:21:44', '2022-11-01 16:21:44');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `products_sku_unique` (`SKU`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=208;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
